#!/usr/bin/env bash
# Regenerates app/src/main/java/io/github/ottershelf/ui/icons/LucideBuiltIn.kt: copies of the
# Lucide icons the app's own UI draws, taken from app/src/main/assets/lucide.txt, so they never wait
# for the full set to be read (ui.icons.Lucide). Edit NAMES, then run from the repo root:
#   bash tools/gen-lucide-builtin.sh
# lucide.txt itself comes from the Nexus app's tools/gen-lucide.ps1 (lucide-static 1.46.0).
set -euo pipefail
cd "$(dirname "$0")/.."
NAMES="ALargeSmall Aperture ArrowLeft Book BookBookmark BookCheck BookCopy BookOpen BookPlus BookX CalendarCheck
CalendarClock CalendarDays Check ChevronDown ChevronRight CircleAlert CircleCheckBig CircleDashed Clock Cloud
CloudOff Download Eye EyeOff Flame FolderOpen Gauge HardDriveDownload Headphones Hourglass House ImageOff Inbox
Info LayoutDashboard Library LibraryBig Lock LogOut Menu Minus Monitor Moon NotebookPen Orbit Palette Pause
Pencil Play Plus RefreshCw RotateCcw RotateCw ScanLine ScrollText Search Settings Sparkles Star Sun
TableOfContents Target Timer Trash TriangleAlert Trophy Users X
Award BookmarkPlus CalendarRange ChartColumn ChartPie ChevronLeft ChevronUp Circle Compass Dna ExternalLink Gem
Globe HardDrive HeartPulse Highlighter Layers ListOrdered Rewind Settings2 Shuffle Swords TabletSmartphone Tag
Tags TrendingDown TrendingUp Waypoints
Brain Contrast Dices Heart Image Quote Share2 Strikethrough Underline WavesHorizontal
ArrowUpDown
LayoutGrid LayoutList"
SRC=app/src/main/assets/lucide.txt
OUT=app/src/main/java/io/github/ottershelf/ui/icons/LucideBuiltIn.kt
{
  echo "package io.github.ottershelf.ui.icons"
  echo ""
  echo "/**"
  echo " * The Lucide icons (lucide-static 1.46.0, ISC licence) the app's own screens draw, copied from"
  echo " * assets/lucide.txt so they never wait for the full set to be read. Same format: stroked path"
  echo " * data, then a tab and filled path data for the few with solid dots."
  echo " * Generated by tools/gen-lucide-builtin.sh: edit the names there, not this file."
  echo " */"
  echo "internal val LUCIDE_BUILT_IN: Map<String, String> = mapOf("
  for n in $NAMES; do
    line=$(grep -m1 "^$n	" "$SRC") || { echo "no icon named $n" >&2; exit 1; }
    data=${line#*	}
    # The tab between stroked and filled data becomes a Kotlin "\t" (a backslash held in a
    # variable, as bash's replacement-string escaping differs between versions).
    bs='\'
    data=${data//\/\\}; data=${data//\"/\\\"}; data=${data//\$/\\$}; data=${data//	/${bs}t}
    echo "    \"$n\" to \"$data\","
  done
  echo ")"
} > "$OUT"
echo "wrote $(echo $NAMES | wc -w) icons to $OUT"
